#!/bin/sh
export ETH32_DIR="/home/rabbit/work/salvation_src_rabbmod"
export ETH32_ET="/home/rabbit/games/et2.55"
export LD_PRELOAD="$ETH32_DIR/libeth32nix.so"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
cd $ETH32_ET

exec ./et.x86 +set fs_game etpub "$@"
unset LD_PRELOAD
